### ISSUE TITLE
Cleaning up code

### ISSUE THREAD

**Issue by Banaanae** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#23]
I came here to report more issues, but it seems they aren't wanted anymore

So I'm instead going to ask, would you be interested if I make a PR updating old scripts to v2, and rather than the script making a v1 gui which gets converted to v2, directly making a v2 gui.

It comes with a few benefits
1. Avoids converter specific bugs
![image](https://github.com/user-attachments/assets/52170034-d11e-487e-bb71-48bd4b030416)
2. Makes maintaining the project, and fixing bugs _heaps_ easier
3. No need for v1 executable

I realise with how this project is, it won't be easy, but in the long run it would significantly improve this project

**Comment by samfisherirl** [comment]
> I came here to report more issues, but it seems they aren't wanted anymore

Not sure what you mean, or what context Im missing. 

> So I'm instead going to ask, would you be interested if I make a PR updating old scripts to v2, and rather than the script making a v1 gui which gets converted to v2, directly making a v2 gui.

> It comes with a few benefits

Well I would be fine with hearing it out, but right now:

1. the only issues are with the original code base and obscure issues with conversion
2. I have made all changes to the converter that have come up in the conversion. 
3. There is no maintenance  I deal with now

If you would like to enumerate conversion errors outside of the one presented I can take it into consideration.  The presented issue will be fixed in likely minutes

**Comment by samfisherirl** [comment]
after a review, I just dont find huge value in building in exceptions and contingencies for built-variables. 
It outputs code, so functionality isnt broken. 
I dont want a solution thats codeless, its just a bridge to the code. Ideally it wouldnt swap, but I forsee needing to rewrite a lot to accomplish and the downside to the user is quite minimal

**Comment by Banaanae** [comment]
This probably isn't really needed anyway
See https://www.autohotkey.com/boards/viewtopic.php?p=506040#p506040

**Comment by samfisherirl** [comment]
> This probably isn't really needed anyway See https://www.autohotkey.com/boards/viewtopic.php?p=506040#p506040

well he hasnt been heard from in a year since saying "im back" and I emailed, and pinged him on the site
