### ISSUE TITLE
When importing or opening a script, aren't I supposed to see the window with the elements?

### ISSUE THREAD

**Issue by LAPIII** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#6]

**Comment by samfisherirl** [comment]
> _No description provided._

@LAPIII 

This was a function of the original code that wasn't fully flushed out. It works 3/4 times for ahkv1, but I cannot easily run that backwards without building it from the ground up. 

Unless something changes, I won't be adding this feature. 

You'll need to use the *Clone Window* function instead of import script. If you use import script, itll need to be an ahkv1 script.
