### ISSUE TITLE
Help File Error

### ISSUE THREAD

**Issue by dougyboy** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#9]
Hi, It appears the code for direction to the help file defaults to C:\Users\dower\Documents\Easy-Auto-GUI-for-AHK-v2\complete_application\Help\AutoHotkey.chm -- Which is not my computer.
![Screenshot_41](https://github.com/samfisherirl/Easy-Auto-GUI-for-AHK-v2/assets/10734066/751e8729-695b-4257-8cc2-eb740a2e51e5)

**Comment by samfisherirl** [comment]
> Hi, It appears the code for direction to the help file defaults to C:\Users\dower\Documents\Easy-Auto-GUI-for-AHK-v2\complete_application\Help\AutoHotkey.chm -- Which is not my computer. ![Screenshot_41](https://user-images.githubusercontent.com/10734066/278989409-751e8729-695b-4257-8cc2-eb740a2e51e5.jpg)

I largely gutted tooltips, help, due to its focus on ahkv1. I tried finding the help menu entry point to redirect to documentation but after a day debugging ended up prioritizing other things. 

I would recommend storing a copy for yourself offline or bookmark the docs website: https://github.com/samfisherirl/Autohotkey-v2-Docs-downloadable-version
